theme = "Tokyonight_Night"

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#585B70"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#A6ADC8"
yellow = "#F9E2AF"

[colors.cursor]
cursor = "#F5E0DC"
text = "#1E1E2E"

[colors.dim]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[colors.hints.end]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.hints.start]
background = "#F9E2AF"
foreground = "#1E1E2E"

[[colors.indexed_colors]]
color = "#FAB387"
index = 16

[[colors.indexed_colors]]
color = "#F5E0DC"
index = 17

[colors.normal]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[colors.primary]
background = "#1E1E2E"
bright_foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
foreground = "#CDD6F4"

[colors.search.focused_match]
background = "#A6E3A1"
foreground = "#1E1E2E"

[colors.search.footer_bar]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.search.matches]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.selection]
background = "#F5E0DC"
text = "#1E1E2E"

[colors.vi_mode_cursor]
cursor = "#B4BEFE"
text = "#1E1E2E"

[env]
TERM = "xterm-256color"

[font]
size = 18.5

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Z"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "X"
mods = "Control|Shift"

[general]
live_config_reload = true
working_directory = "/Users/danielshields/"

[terminal]

[scrolling]
history = 10000
multiplier = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = """,│`|:"' ()[]{}<>"""

[terminal.shell]
args = ["-l", "-c", "tmux attach || tmux new -s '󰘧'"]
program = "/bin/zsh"

[window]
decorations = "Buttonless"
opacity = 0.85

[window.padding]
x = 10
y = 10

[keyboard]
